services:
  - type: web
    name: todo-backend
    env: docker
    sourceDir: backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8001
      - key: MONGO_URI
        value: mongodb://mongo:27017/todo-app
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d

  - type: web
    name: todo-frontend
    env: docker
    sourceDir: frontend
    envVars:
      - key: VITE_API_URL
        value: https://todo-backend.onrender.com/api

  - type: redis
    name: mongo
    env: docker
    image: mongo:latest
    envVars:
      - key: MONGO_INITDB_DATABASE
        value: todo-app
